const labels: Record<any, string> = {
  "Home": "Home",
  "ThisMonthSpend": "This month spend",
  "Expenses": "Expenses",
  "AddExpense": "Add Expense",
  "EnterExpenseName": "Enter expense name",
  "Name":"Name",
  "Category": "Category",
  "Amount": "Amount",
  "EnterAmount": "Enter amount",
  "ModeOfPayment": "Mode Of Payment",
  "ModeLabel": "mode",
  "BeforeStart": "Before we start",
  "EnterName": "Enter your name",
  "ChooseCurrency": "Choose currency",
  "History": "History",
  "NoItems": "No items",
  "Statistics": "Stats",
  "Profile": "Profile",
  "ComingSoon": "Coming Soon",
  "AddSuccess": "Added Successfully",
  "AddItemsMessage": "Add some expenses to see statistics.",
  "Currency": "Currency",
  "Summary": "Summary",
  "BudgetMessage": "what's your montly budget?",
  "EnterBudget": "Enter budget",
  'Budget': 'Budget',
  'Balance': 'Balance',
  'Left': 'left',
  'OverSpent': 'over spent',
  'Last10': 'Last 10 transactions',
  'UpdatedDetails': 'Updated successfully',
  'Save': 'Save',
  'Edit': 'Edit',
  'Delete': 'Delete',
  'Filters': 'Filters',
  'Apply': 'Apply',
  'Clear': 'Clear',
  'StartDate': 'Start Date',
  'EndDate': 'End Date',
  'SearchWithName': 'Search with name',
  'Date': 'Date',
  'DateError': 'start date should be less than end date'
}

export default labels